---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create database subnet group
      rds_subnet_group:
        state: present
        region: "us-east-2"
        name: "ig-Module5-rds-subnet-group"
        description: Private subnet group for RDS
        subnets:
          - "{{private_subnet_1.subnet.id}}"
          - "{{private_subnet_2.subnet.id}}"
      register: subnet_group

    - name: Create postgres RDS instance
      rds_instance:
        allocated_storage: 20
        db_instance_identifier: "ig-Module5-image-gallery"
        db_instance_class: db.t2.micro
        db_name: "imagegallery"
        db_subnet_group_name: "{{subnet_group.subnet_group.name}}"
        engine: postgres
        password: "{{ lookup('aws_secret', 'ig/m5/postgres/admin') | from_json | json_query('password') }}"
        username: "{{ lookup('aws_secret', 'ig/m5/postgres/admin') | from_json | json_query('username') }}"
        region: "us-east-2"
        vpc_security_group_ids:
          - "{{postgres_sg.group_id}}"
      register: rds

    - name: Set postgres admin dictionary
      set_fact:
        postgres_admin_secret: |-
          {
            "username": "{{ lookup('aws_secret', 'ig/m5/postgres/admin') | from_json | json_query('username') }}",
            "password": "{{ lookup('aws_secret', 'ig/m5/postgres/admin') | from_json | json_query('password') }}",
            "engine": "postgres",
            "host": "{{ rds.endpoint.address }}",
            "port": 5432,
            "dbInstanceIdentifier": "image-gallery"
          }
    - name: Set image gallery dictionary
      set_fact:
        image_gallery_secret: |-
          {
            "username": "{{ lookup('aws_secret', 'ig/m5/postgres/imagegallery') | from_json | json_query('username') }}",
            "password": "{{ lookup('aws_secret', 'ig/m5/postgres/imagegallery') | from_json | json_query('password') }}",
            "engine": "postgres",
            "host": "{{ rds.endpoint.address }}",
            "port": 5432,
            "dbInstanceIdentifier": "image-gallery",
            "dbname": "imagegallery"
          }

    - name: Set secrets manager db information (admin)
      aws_secret:
        name: "ig/m5/postgres/admin"
        region: "us-east-2"
        secret: "{{ postgres_admin_secret | to_json }}"

    - name: Set secrets manager db information (user)
      aws_secret:
        name: "ig/m5/postgres/imagegallery"
        region: "us-east-2"
        secret: "{{ image_gallery_secret | to_json }}"