---
- hosts: all
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: "ig-Module5-VPC"
        cidr_block: 10.10.0.0/16
        region: "us-east-2"
        tags:
          Module: 5
      register: vpc
    - name: Create public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        cidr: 10.10.1.0/24
        tags:
          Name: "ig-Module5-Public-SN-1"
      register: public_subnet_1
    - name: Create public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        cidr: 10.10.2.0/24
        tags:
          Name: "ig-Module5-Public-SN-2"
      register: public_subnet_2
    - name: Create private subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        cidr: 10.10.3.0/24
        tags:
          Name: "ig-Module5-Private-SN-1"
      register: private_subnet_1
    - name: Create private subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        cidr: 10.10.4.0/24
        tags:
          Name: "ig-Module5-Private-SN-2"
      register: private_subnet_2
    - name: Create internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc.vpc.id}}"
        tags:
          Name: "ig-Module5-igw"
          Module: 5
      register: igw
    - name: Create NAT gateway
      ec2_vpc_nat_gateway:
        vpc_id: "{{vpc.vpc.id}}"
        subnet_id: "{{public_subnet_1.subnet.id}}"
        tags:
          Name: "ig-Module5-nat"
          Module: 5
      register: nat
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: us-east-2
        tags:
          Name: Module 5 Public Route Table
        subnets:
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table
    - name: Set up private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: us-east-2
        tags:
          Name: Module 5 Private Route Table
        subnets:
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            instance_id: "{{ nat.instance_id }}"
      register: private_route_table
    - name: Create public network acl
      ec2_vpc_nacl:
        vpc_id: "{{vpc.vpc.id}}"
        name: "ig-Module5-public-nacl"
        region: us-east-2
        subnets:
          - "{{public_subnet_1.subnet.id}}"
          - "{{public_subnet_2.subnet.id}}"
        tags:
          Module: 5
        ingress:
            # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code,
            #                                             port from, port to
            - [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22]
            - [200, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80]
            - [300, 'icmp', 'allow', '0.0.0.0/0', 0, 8]
        egress:
            - [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null]
    - name: Create private network acl
      ec2_vpc_nacl:
        vpc_id: "{{vpc.vpc.id}}"
        name: "ig-Module5-private-nacl"
        region: us-east-2
        subnets:
          - "{{private_subnet_1.subnet.id}}"
          - "{{private_subnet_2.subnet.id}}"
        tags:
          Module: 5
        ingress:
            # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code,
            #                                             port from, port to
            - [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22]
            - [200, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80]
            - [300, 'icmp', 'allow', '0.0.0.0/0', 0, 8]
        egress:
            - [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null]